mod.17.01.15 modules_event

diff --git a/usr/sbin/unload_sfs b/usr/sbin/unload_sfs
--- a/usr/sbin/unload_sfs
+++ b/usr/sbin/unload_sfs
@@ -1,1 +1,106 @@
-unload_pfs
+#!/bin/bash
+#idea jcoder24 20080412
+#modified 20090222
+#DdShurick modified 20100924 for PuppyRus-2, 08.26.2012 for Richy-217, 11.05.2012 for .pfs, 15.01.2015 for all squasfs module
+#
+self="Отключить модуль"
+if [ "$1" = "" ]; then echo "Не указан модуль."
+exit 1
+fi
+fs_module=$(basename "$1")
+mount_point="/mnt/live/memory/images/$fs_module" #<-- здесь
+if [ ! -d "$mount_point" ]; then
+xpupsay "$fs_module не был подключен."
+exit 1
+fi
+#--- Останавливаем программу перед отмонтированием---
+if [ -f "$mount_point"/stop.sh ];then 
+"$mount_point"/stop.sh
+fi
+find $mount_point/ -type f -executable | while read P
+do
+Ppid="$(pidof $(basename $P))" || continue 
+kill $Ppid
+done
+#--- Check args and requirements ---
+if [ "$(file "$1" | grep "Squashfs filesystem")" = "" ] ; then
+   echo "$1 не squashfs."
+   exit 1
+else
+   if [ `echo $1 | grep -ice ".${FS}$"` -ne 1 ]; then
+      echo "Usage: $self file$FS"
+      exit 1
+   elif [ ! -f "$1" ]; then
+      if [ -L "$1" ]; then
+      	echo "Symbolic Link target not found!"
+      else
+      	echo "File not found!"
+      fi
+      exit 1
+   fi
+fi
+
+xpupsay "Идет отключение модуля $fs_module" &
+
+sudo mount -o remount,del:"$mount_point"/ /
+
+XRESTART=""
+
+	#- update ld.conf.so (libraries)
+	if [ ! -z "`which ldconfig`" ]; then
+	 	if [ -d  "$mount_point/usr/lib" -o -d "$mount_point/usr/local/lib" ]; then
+	 		echo "Updating library cache /etc/ld.so.cache..."
+	 		ldconfig
+	 	fi
+	fi
+	
+	#- update/refesh menus 
+	if [ `find "$mount_point" | grep -ic "desktop$"` -gt 0 ] 
+	then
+		fixmenus
+		icewm 
+	fi
+	
+	#- make new kernel modules available, must still be loaded when needed
+	kernel_version="`uname -r`"
+	if [  `find "$mount_point/lib/modules/$kernel_version" 2>/dev/null | grep -ic "ko$"` -gt 0 ]; then
+		echo "Running depmod...."
+		depmod
+	fi
+
+	#make new fonts available
+	for font_dir in "/usr/X11R6/lib/X11/fonts/TTF" "/usr/share/fonts/default/TTF"
+	do
+		if [ -d "$mount_point/$font_dir" ]; then
+			cd "$font_dir"
+			`which mkfontscale` .
+			`which mkfontdir` .
+		fi
+	done
+
+sudo umount -d "$mount_point" 
+sudo rmdir "$mount_point"
+
+[ -x /usr/local/bin/refreshDesktopIcons ] && /usr/local/bin/refreshDesktopIcons
+
+# dim-kut ----
+fs_path=$(dirname "$1")
+parent_dir2=${fs_path:0:1}
+FULL_PATH="$1"
+
+if [ $parent_dir2 == '.' ] # если путь начинается с ./
+then
+pwd_path="`pwd`"
+fs_name=`basename "$1"`
+FULL_PATH="${pwd_path}/${fs_name}"
+fi
+# dim-kut ---+DdShurick add--
+if [ -d /usr/local/sfs_event ];then
+ if [ "$(ls /usr/local/sfs_event/sfs_scripts | grep $fs_module)" = "" ]; then 
+/usr/local/sfs_event/sfs_remove "$FULL_PATH"
+ else
+mv -f $HOME/.icewm/menu $HOME/.icewm/menu-previous
+sed "s/ok.xpm\" \/usr\/local\/sfs_event\/sfs_scripts\/dlg-$fs_module/error.xpm\" \/usr\/local\/sfs_event\/sfs_scripts\/reload-$fs_module/" $HOME/.icewm/menu-previous > $HOME/.icewm/menu
+ fi
+fi
+xpupsay "Успешно! Модуль $fs_module отключен." &
